#!/bin/bash
LAST_CHAPTER=100
#LAST_CHAPTER=$(grep [0-9] ../last_chapter.txt)
CHAPTER=${1?"missing: the three digit 001-$LAST_CHAPTER"}
while [ $CHAPTER -le $LAST_CHAPTER ]
do
TITLE=$(grep ^$CHAPTER coverparameters.txt | awk '{print $2;}' | sed 's#_#/#')
../get_wikisource.py $TITLE
CHAPTER=$(printf "%03d" `expr $CHAPTER + 1`)
done
