#!/bin/bash
BOOK=唐詩三百首
if [[ -d $BOOK ]]; then :; else
mkdir $BOOK;
fi
BOOK_URL="https://zh.wikisource.org/wiki/$BOOK"
cd $BOOK
curl -o book.html $BOOK_URL
grep -e "^<li>.*href=.*title=" book.html  | \
sed -e 's/.*<li>\([^<]*\)<.*title="\([^"]*\)">\([^<]*\)<[^>]*>\([^<]*\).*/\2,\1\3\4/' \
  -e 's#/#_#g' | nl -n rz -w 3 -s "," > coverparameters.txt
node ../getlast_poet.js > last_chapter.txt 
cat book.html  | grep 作者： | sed 's/.*Author:\([^%][^（]*\).*/\1/' > author.txt
if [[ -d original ]]; then 
   rm original/*txt
else
   mkdir original
fi
echo OK! Now we have to run the following command
echo     firefox -P 
echo Choose profile wikisource then start firefox.
echo In the Downloads section of the Preference menu.
echo make sure that the Save to option is ticked.
echo and amend the save to directory to be
echo    $HOME/wikisource/$BOOK/original
echo Close the firefox and we should be good to continue
echo If you understand what you should do,
echo    press RETURN key to run firefox -P .
read
firefox -P
source ../venv/bin/activate
LAST_CHAPTER=$(grep [0-9] last_chapter.txt)
CHAPTER=001
while [ $CHAPTER -le $LAST_CHAPTER ]
do
TITLE=$(grep ^$CHAPTER coverparameters.txt | awk 'BEGIN { FS="," } {print $2;}' | sed -e 's#_#/#g' -e 's/ /\\ /g')
../get_wikisource.py "$TITLE"
CHAPTER=$(printf "%03d" `expr $CHAPTER + 1`)
done
deactivate
cp ../cutnsave .
vim cutnsave
./cutnsave
echo Congratulations! You have completed the first major step of $BOOK
echo You better review author.txt, last_chapter.txt, coverparameters.txt
echo and these $BOOK_* which should not contain anything besides the content of chapters
echo before issue
echo ./create_the_audio_book.sh $BOOK  
echo to finish the entire project.
