#!/bin/bash --verbose
BOOK=${1?"missing book name"}
if [[ -d $BOOK ]]; then :; else
mkdir $BOOK;
fi
BOOK_URL="https://zh.wikisource.org/wiki/$BOOK"
curl $BOOK_URL | grep -e "<li><a href=.*title="\""$BOOK" | \
sed 's/.*<li>\([^<]*\)<.*title="\([^"]*\)">\([^<]*\)<[^>]*>\([^<]*\).*/\2 \1\3\4/' | \
nl -n rz -w 3 -s " " > $BOOK/coverparameters.txt