#!/bin/bash
LAST_CHAPTER=$(grep [0-9] ../last_chapter.txt)
CHAPTER=${1?"missing: the three digit 001-$LAST_CHAPTER"}
ORIG_DIR=$(pwd)
AUTHOR=$(cat ../author.txt)
while [ $CHAPTER -le $LAST_CHAPTER ]
do
TITLE=$(grep ^$CHAPTER ../coverparameters.txt | awk '{print $3;}')
BOOK=$(pwd | tr -d [A-Za-z]/)
DATE=$(date +%F)
mid3v2 -a "$AUTHOR" -t "$TITLE" -A "【$BOOK】全本廣東話原文照讀" -g "101" -y $DATE -T "$CHAPTER/$LAST_CHAPTER" $CHAPTER.mp3
CHAPTER=$(printf "%03d" `expr $CHAPTER + 1`)
done
